### ISSUE TITLE
option for generating sourcemaps?

### ISSUE THREAD

**Issue by zaszlo** [paulchathaway/less-watch-compile#1]
lessc has an option to generate the very handy soucemaps, is there a way to set that for this watcher as well?

**Comment by pawlh** [comment]
Sorry for taking so long to respond.
Definitely! When I first wrote this, I was filling a very niche need.
Over the next few days I am going to fix a growing list of issues. When I push those changes, I'll include sourcemaps in the mix as well.

**Comment by pawlh** [comment]
Thanks for the suggestion!
less-watch-compile was just updated to include a toggle for generating sourcemaps.
