### ISSUE TITLE
Target file gets cleared out every other save.

### ISSUE THREAD

**Issue by SamSteele01** [paulchathaway/less-watch-compile#2]
I'm using less-watch-compile in conjunction with create-react-app. I added the scripts below in package.json. 

![screenshot from 2018-03-09 15-02-41](https://user-images.githubusercontent.com/29762972/37227611-ea20b86a-23ab-11e8-9920-e9874594b1eb.png)

Every other save event in App.less causes the contents of the target (App.css) to be cleared out. I thought that maybe it was an issue with npm-run-all, but the following is from running `npm run watch-css`

![screenshot from 2018-03-09 15-00-32](https://user-images.githubusercontent.com/29762972/37227817-83ece8f6-23ac-11e8-8bcc-f5caae425df2.png)

The `compiled in 1ms` or `6ms` is when the target contents get deleted. It is also doing it when I run the command directly.

![screenshot from 2018-03-09 15-26-31](https://user-images.githubusercontent.com/29762972/37228379-6e32a558-23ae-11e8-867c-1b15f4db91ff.png)

Is this an issue with versions?

**Comment by pawlh** [comment]
After a brief test, I was quickly able to replicate your problem. I am unsure of the cause, especially considering I do not recall seeing this issue a couple years ago. Even using the original version this project was built on (being less@2.7.1), the problem remains. 

This project has been collecting dust for a couple years and is due for a fine-tooth comb-through; it appears that it is time that I do that.
Thanks for bringing this to my attention!

**Comment by pawlh** [comment]
For whatever reason, fs.readFile was sporadically returning empty contents. The fix is hacky, but executing fs.stats on the file prior to reading the contents seems to prevent the problem from occurring.
