### ISSUE TITLE
while index.less file change   ,  this not work ...

### ISSUE THREAD

**Issue by plh97** [paulchathaway/less-watch-compile#3]
![176452006519559363](https://user-images.githubusercontent.com/14355994/37440362-4ee72e84-2837-11e8-9d23-7c7e8cbe4df4.png)

while index.less file change , this not work ... #3

yeah,,,,it work  fine  in the last week  ,   
i   do nothing,
maybe i need to read your core code && rewrite another one ....

**Comment by plh97** [comment]
thanks for your code inspire my mind to write nodejs  file to    cover less to css

**Comment by pawlh** [comment]
Hi @pengliheng!
This project currently has a host of issues to be resolved, but I think that this particular one is not one of them. I think you might be using a different NPM project with a [similar name](https://www.npmjs.com/package/less-watch-compiler).

Looking at your screenshot, the syntax you use in your command and the [output](https://github.com/jonycheung/deadsimple-less-watch-compiler/blob/77f3ab1038a492f84c77fc0f45d77620bc79a519/src/less-watch-compiler.js#L103) of less-watch-compiler matches the project I linked to above.

Best of luck with your projects!
